# Generated by Django 2.2 on 2020-04-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullname',
        ),
    ]
